export const FILTER_TRANSFERS_ALL = "all";
export const FILTER_TRANSFERS_NONE = "0";
export const FILTER_TRANSFERS_ONE = "1";
export const FILTER_TRANSFERS_TWO = "2";
export const FILTER_TRANSFERS_THREE = "3";
export const FILTER_TRANSFERS_ALL_OPTIONS = [
  FILTER_TRANSFERS_ALL,
  FILTER_TRANSFERS_NONE,
  FILTER_TRANSFERS_ONE,
  FILTER_TRANSFERS_TWO,
  FILTER_TRANSFERS_THREE,
];

export const SORTING_TICKETS_BY_CHEAPEST = "cheapest";
export const SORTING_TICKETS_BY_FASTEST = "fastest";
export const SORTING_TICKETS_OPTIMAL = "optimal";
